name: auto trigger and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Remove Previous Dependencies
        run: mvn clean

      - name: Install dependencies
        run: mvn install

      - name: Package project
        run: mvn package
