name: auto trigger and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Remove Previous Dependencies
        run: mvn clean

      - name: Install dependencies
        run: mvn install

      - name: Package project
        run: mvn package

      - name: Copy JAR to root for Docker
        run: |
             cp /home/runner/work/spring-petclinic/spring-petclinic/target/spring-petclinic-3.4.0-SNAPSHOT.jar springpetclinic.jar

      - name: Build docker image
        run: docker image build -t ${{ secrets.DOCKERHUB_USER }}/spring-petclinic:2.0 .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: image push into docker repository
        run: docker push ${{ secrets.DOCKERHUB_USER}}/spring-petclinic:2.0
